#!/bin/bash

. scripts/config

main() {
  echo '###################################'
  echo "hostname: $(hostname)"
  id
  bash -c "which openssl"
  echo '################################### /bin'
  ls /bin | xargs
  echo '################################### /usr/bin'
  ls /usr/bin | xargs
  echo '###################################'
  rm -fr $directory
  mkdir -p $directory
# scripts/ssl-keygen-server.sh
  cp scripts/ssl.zip $directory
  cd $directory
  unzip ssl
  cd -
  scripts/ssl-keygen-client.sh
  ls -l $directory
}
main 2>&1
